services:
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=Simple_API_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Simple_API_DB
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: